export const SET_CURRENT_ALBUM = 'SET_CURRENT_ALBUM';
export const REMOVE_CURRENT_ALBUM =  'REMOVE_CURRENT_ALBUM';
export const MAKE_FAVORITE = 'MAKE_FAVORITE';
export const SHOW_ERROR = 'SHOW_ERROR';
export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_ITEMS_WITH_ERROR = 'LOAD_ITEMS_WITH_ERROR';
